blog:
  build: .
  volumes:
    - /tmp
  user: uwsgi
  command: uwsgi --die-on-term --ini /data/conf/uwsgi/blog.ini
nginx:
  build: .
  dockerfile: conf/nginx/Dockerfile
  ports:
    - "80:80"
postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=random_password
