version: '2'
services:
  blog:
    volumes:
      - /tmp
      - ./backend:/data
  nginx:
    volumes:
      - ./frontend/dist:/app/dist
  frontend:
    build: frontend
    command: npm start
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/typings.json:/app/typings.json
      - ./frontend/gulpfile.ts:/app/gulpfile.ts
      - ./frontend/dist:/app/dist
