blog:
  extends:
    file: base.yml
    service: blog
  volumes:
    - /tmp
    - /data/blog/static
    - .:/data
nginx:
  extends:
    file: base.yml
    service: nginx
postgres:
  extends:
    file: base.yml
    service: postgres
