blog:
  build: .
  ports:
    - "80:80"
  volumes:
    - /home/rancher/storage:/storage
jenkins:
  ports:
  - 8082:8080/tcp
  restart: 'no'
  tty: true
  image: jenkins
  privileged: true
  volumes:
  - /data/jenkins:/var/jenkins_home
  - /var/run/docker.sock:/var/run/docker.sock
  - /usr/bin/docker:/usr/bin/docker
  stdin_open: true
  user: root
