version: '2'
services:
  backup:
    image: postgres
    links:
      - postgres
    volumes:
      - ./:/tmp
    environment:
      - PGPASSWORD=random_password
    command: pg_dump -U postgres -h postgres postgres
  restore:
    image: postgres
    links:
      - postgres
    volumes:
      - /tmp:/tmp
    environment:
      - PGPASSWORD=random_password
    command: psql -U postgres -h postgres -f /tmp/backup.sql postgres
